### ISSUE TITLE
An option to trigger alerts & autojoin based on spectator spots

### ISSUE THREAD

**Issue by Daggerfin** [maesse/ns2ping-web#2]
This is less of an issue, more of a feature request to meet current server behaviors.

Most of the servers that remain populated have limited free access to three spectators, reserving the other two slots for VIP members. This limit in conjunction with the now lower NS2 player base causes a unique issue where joining a reasonably populated server requires waiting in a spectator queue. This makes NS2ping-web (and ns2browser.com) slightly less useful, where you are unable to get into a server for a longer period of time due to the spectator queue constantly filling up. When players eventually manage to join a server without a spectator queue, it often indicates that the server is losing players, compromising the gaming experience.

The proposed solution involves implementing a feature in the ns2ping-web system: a checkbox that modifies the criteria for considering a server as joinable. Specifically, when the number of spectators reaches 2, the system would treat the server as joinable (indicated by an open eye icon), thus alerting players or activating an autojoin function. This adjustment aims to streamline the process of entering the spectator queue, thereby enhancing player convenience and potentially improving overall gameplay by facilitating easier access to populated servers.

**Comment by maesse** [comment]
Hi Daggerfin

Thanks for your proposal

This is already a core feature of the tool/project, so I'm curious to hear how this fails for you or if I'm misunderstanding you?

The "Is this server joinable?" code that triggers auto-join and sound cues is based on there being 3 public spectator slots for most servers (I hardcoded 5 slots specifically for TTO), so basically, if you can join the server without being kicked then it should be "joinable" from ns2browser.com perspective. This is what you're requesting, right?

The calculation is something like this:
Server max player slots: 20
Server max spectator slots: 5

ns2browser.com expects only 3 of the spectator slots to be joinable, so total max players would be 23

If the server is sitting at 23 and then drops to 22, it will trigger auto-join and play sound cues

At least that is the expected behavior 😃 

Usually if this isn't working it's because someone else snatched the free slot before you were able to join, and in that case it's limited what I can do besides maybe ping the server more often. It's set to check every 3 seconds, but potentially I could lower it to 1 second which I think is what the in-game browser does. 

I've been meaning to fix some minor issues on the site for a while, so let me know what your thoughts are and I can incorporate it in the next update.

**Comment by Daggerfin** [comment]
First and foremost, thank you for your response. I genuinely appreciate the time and expertise you have invested in this project and for addressing my feedback.

It appears that I was hasty in providing my feedback. The ns2browser functions precisely as you described, rendering my feedback, embarrassingly, unnecessary. I apologize for my oversite and assumptions.

**Comment by maesse** [comment]
No problem Daggerfin, your request prompted me to do the little upgrade on the site I had been thinking about anyways :) Thanks for using the site and your kind words!
